/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    void registrar_uauari(nom_usuari, correu_electronic) {
        App classUnderTest = new App();
        
    }
    void eliminar_usuari(nom_usuari) {
        App classUnderTest = new App();
        
    }

    registrar_habitacio(numero, tipus, preu) {
        App classUnderTest = new App();
    }
    eliminar_habitacio(numero) {
        App classUnderTest = new App();
    }
    llistar_habitacions() {
        App classUnderTest = new App();
    }

    fer_reserva(numero_habitacio, usuari) {
        App classUnderTest = new App();
    }
}
