/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test
    void registrar_usuari(nom_usuari, correu_electronic) {
        App classUnderTest = new App();
        assertTrue(usuario_creado);
    }

    @Test
    void eliminar_usuari(nom_usuari) {
        App classUnderTest = new App();
        asserTrue(usuario_eliminado);
    }

    @Test
    void registrar_habitacio(numero, tipus, preu) {
        App classUnderTest = new App();
        assertTrue(habitaion_registrada);
    }

    @Test
    void eliminar_habitacio(numero) {
        App classUnderTest = new App();
        assertTrue(habitacion_eliminada);
    }

    @Test
    void llistar_habitacions() {
        App classUnderTest = new App();
        
    }

    @Test
    void fer_reserva(numero_habitacio, usuari) {
        App classUnderTest = new App();
        asserTrue(reserva_hecha);
    }

    @Test
    void visualitza_reserves(usuari) {
        App classUnderTest = new App();
        asserTrue(reserva_hecha);
    }
}
