/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    void SumaCorrecta() {
        App classUnderTest = new App();
        assertEquals(6, classUnderTest.sumar(3,3));
    }
    void RestaCorrecta() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.sumar(6,3));
    }
}
